---
title: "BUSCO"
author: "Alex Caswell"
date: "2025-04-25"
output: html_document
---

```{r setup}

library(tidyverse)
library(ggtext)

```

```{r get_files}

# These are generated from files in data/busco_summaries using python/generate_tsv_from_busco_summaries.py

busco_r003 <- read_tsv("data/busco_tsv/RAMAN_R003.tsv")
busco_r004 <- read_tsv("data/busco_tsv/RAMAN_R004.tsv")
busco_r005 <- read_tsv("data/busco_tsv/RAMAN_R005.tsv")
busco_r007 <- read_tsv("data/busco_tsv/RAMAN_R007.tsv")
busco_r012 <- read_tsv("data/busco_tsv/RAMAN_R012.tsv")
busco_r018 <- read_tsv("data/busco_tsv/RAMAN_R018.tsv")

busco_all <- rbind(
  busco_r003,
  busco_r004,
  busco_r005,
  busco_r007,
  busco_r012,
  busco_r018
) %>% mutate(MIMAG = ifelse(Complete > 90 & Multiple < 5, "HQ", ifelse(Complete > 50 & Multiple < 10, "MQ", "LQ"))) %>%
  mutate(MIMAG = fct_relevel(MIMAG, "HQ", "MQ", "LQ"))
  
#busco_genes <- read_tsv("data/busco_genes/all_genes.tsv")

```

A few are missing!!! I need to re-run BUSCO on these!!

r003: 67, 74, 89
r004: 93

```{r histogram_of_completeness}

completeness <- ggplot(busco_all, aes(x = `Complete`, fill=SampleName)) +
  geom_histogram(binwidth = 10, boundary = 0, closed = "left", col="black") + 
  scale_x_continuous(breaks = seq(0, 100, 10)) +
  scale_y_continuous(breaks = seq(0, 250, 20)) + 
  scale_fill_brewer(palette = "Set1") + 
  coord_flip() +
  ylab("\\# of MAGs") +
  xlab("Completeness (%)") +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 12),
    axis.text.x = element_markdown(size = 12),
    axis.title.x = element_markdown(size = 14),
    axis.title.y = element_blank(),#element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef00'),
    plot.background = element_rect(fill = '#fff7ef00'),
    legend.background = element_rect(fill = '#fff7ef00'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank(),
    plot.margin = margin(l = 20),
  )

completeness
ggsave("graphs/busco/mag_busco_completeness_histogram.png", completeness)

```

```{r boxplot_of_completeness}

boxplot_completeness <- ggplot(busco_all, aes(x = `SampleName`, y=Complete, fill=SampleName)) +
  geom_boxplot(alpha = 0.8, show.legend = FALSE) + 
  scale_y_continuous(breaks = seq(0, 150, 20)) + 
  scale_fill_brewer(palette = "Set1") + 
  xlab("") +
  ylab("Completeness (%)") +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 14),
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef00'),
    plot.background = element_rect(fill = '#fff7ef00'),
    legend.background = element_rect(fill = '#fff7ef00'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank(),
  )

ggsave("graphs/busco/mag_busco_completeness_boxplot.png", boxplot_completeness)
boxplot_completeness

```

```{r completeness_panel}

completeness_panel <- plot_grid(boxplot_completeness, completeness, labels = c("A", "B"), rel_widths = c(1, 1.1))

ggsave("graphs/busco/completeness_panel.png", completeness_panel, units = "px", width = 2800, height = 1200)
completeness_panel

```

```{r histogram_of_genes}

histogram_genes <- ggplot(busco_genes, aes(x = `Genes`, fill=SampleName)) +
  geom_histogram(bins = 50, boundary = 0, closed = "left", col="grey") + 
  scale_x_continuous(breaks = seq(0, 50000, 5000)) +
  scale_y_continuous(breaks = seq(0, 150, 25)) + 
  scale_fill_brewer(palette = "Set1") + 
  ylab("Count") +
  xlab("Number of CDSs") +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 20),
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank(),
  )

histogram_genes

```


```{r boxplot_of_genes}

boxplot_genes <- ggplot(busco_genes, aes(x = `SampleName`, y=Genes, fill=SampleName)) +
  geom_boxplot() + 
  scale_y_continuous(breaks = seq(0, 20000, 2000)) + 
  scale_fill_brewer(palette = "Set1") + 
  xlab("") +
  ylab("Genes Per Bin") +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 20),
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank(),
  )

boxplot_genes

```

```{r barchart_mimags}

mimag_barchart <- ggplot(busco_all, aes(x = SampleName, fill = MIMAG)) + 
  geom_bar(position = "fill")

mimag_barchart


```