---
title: "GCMS"
output: html_document
date: "2025-06-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}

library("tidyverse")
library("GCalignR")
library("vegan")
library("pheatmap")
library("dendextend")
library("devtools")

#devtools::install("C:\\users\\horat\\desktop\\MetaboAnalystR", build = TRUE, build_vignettes = TRUE, build_manual =T)
library("MetaboAnalystR")

```

```{r get_peak_lists}

chemstation_list_input <- list()

for (filename in list.files("data/gcms/ChemStation")) {
  sample <- read_tsv(paste0("data/gcms/ChemStation/", filename), skip = 4)
  colnames(sample) <- c("Peak", "RT", "Type", "Width", "Area", "Start", "End")
  chemstation_list_input[str_extract(filename, "[R]+[0-9]+[_]+[0-9]+")] <- list(sample[, c(2, 5)])
}

openchrom_raw <- list()

for (filename in list.files("data/gcms/OpenChrom")) {
  sample <- read_tsv(paste0("data/gcms/OpenChrom/", filename), skip = 1, col_names = FALSE)
  colnames(sample) <- c("RT", "Area")
  openchrom_raw[str_extract(filename, "[R]+[0-9]+[_]+[0-9]+[a-z]?")] <- list(sample[, c(1, 2)])
}


```

```{r align_chromatograms}

# Input makes sense
check_input(data = openchrom_raw, plot = F)

# How far apart are neighboring peaks in (within) each of these samples?
peak_interspace(data = openchrom_raw, rt_col_name = "RT", quantile_range = c(0.0, 0.8), quantiles = 0.05)

# ChemStation: Looks like there are a lot of close peaks. min_diff_peak2peak = 0.02
# OpenChrom: Not as close! min_diff_peak2peak = 0.05

openchrom_aligned <- align_chromatograms(data = openchrom_raw,
  rt_col_name = "RT",
  min_diff_peak2peak = 0.05,
  max_diff_peak2peak = 0.05,
  delete_single_peak = TRUE
)

```

```{r visualize}

gc_heatmap(openchrom_aligned)

plot(openchrom_aligned, which_plot = "all")

```

```{r normalize}

openchrom_normalized <- norm_peaks(openchrom_aligned, conc_col_name = "Area", rt_col_name = "RT", out = "data.frame")
openchrom_normalized <- log(openchrom_normalized + 1)

```


```{r ordination}

openchrom_nmds <- metaMDS(comm = openchrom_normalized, distance = "bray")

ggplot(as.data.frame(openchrom_nmds[["points"]]), aes(x = MDS1, y = MDS2, label = rownames(as.data.frame(openchrom_nmds[["points"]])))) +
  geom_point() + 
  geom_text(position = position_jitter(height = 0.0))

```


```{r heatmap}

openchrom_normalized_t <- as.data.frame(t(openchrom_normalized))
mz <- rownames(openchrom_normalized_t)

dist_rows.euclid <- dist(openchrom_normalized_t, method = "euclidean")
dist_rows.manhattan <- dist(openchrom_normalized_t, method = "manhattan")
dist_rows.pearson <- dist(1 - cor(openchrom_normalized_t, method = "pearson"))

row_clusters.euclid <- hclust(dist_rows.euclid, method = "complete")
row_clusters.manhattan <- hclust(dist_rows.manhattan, method = "complete")
row_clusters.pearson <- hclust(dist_rows.pearson, method = "complete")


dist_cols.euclid <- dist(openchrom_normalized, method = "euclidean")
dist_cols.manhattan <- dist(openchrom_normalized, method = "manhattan")
dist_cols.pearson <- dist(1 - cor(openchrom_normalized, method = "pearson"))

col_clusters.euclid <- hclust(dist_cols.euclid, method = "complete")
col_clusters.manhattan <- hclust(dist_cols.manhattan, method = "complete")
col_clusters.pearson <- hclust(dist_cols.pearson, method = "complete")

pheatmap(as.matrix(openchrom_normalized_t),
         cluster_rows = FALSE,# row_clusters.euclid,
         cluster_cols = TRUE,
         clustering_distance_cols = "manhattan",
         #filename = "graphs/gcms/dendrogram_heatmap.png"
         )

```


```{r metaboanalystr}

openchrom_normalized_specbins <- openchrom_normalized %>%
  add_column(SampleName = rownames(openchrom_normalized), .before = c(1)) %>%
  add_column(SampleGroup = str_extract(rownames(openchrom_normalized), "[R]+[0-9]+"), .before = c(2))

write_csv(openchrom_normalized_specbins, "data/gcms/specbins.csv")


```