---
title: "HUMAnN"
output: html_document
date: "2025-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports, results = 'hide'}

library(tidyverse)
library(vegan)
source("humann_utils.r")

```

```{r get_pathabundance_files, results = 'hide'}

humann_prodigal <- data.frame()

for (filename in list.files("data/humann_wnanolyse/prodigal/")) {
  if (grepl("pathabundance", filename)) {
    if (length(humann_prodigal) == 0) {
      humann_prodigal <- read_tsv(paste0("data/humann_wnanolyse/prodigal/", filename), col_names = TRUE)
      colnames(humann_prodigal) <- c("Pathway", "Relative Abundance")
      humann_prodigal <- add_column(humann_prodigal, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      pathabundance <- read_tsv(paste0("data/humann_wnanolyse/prodigal/", filename), col_names = TRUE)
      colnames(pathabundance) <- c("Pathway", "Relative Abundance")
      pathabundance <- add_column(pathabundance, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_prodigal <- rbind(humann_prodigal, pathabundance)
    }
  }
}

humann_100bp_shreds <- data.frame()

for (filename in list.files("data/humann_wnanolyse/shredded_100bp/")) {
  if (grepl("pathabundance", filename)) {
    if (length(humann_100bp_shreds) == 0) {
      humann_100bp_shreds <- read_tsv(paste0("data/humann_wnanolyse/shredded_100bp/", filename), col_names = TRUE)
      colnames(humann_100bp_shreds) <- c("Pathway", "Relative Abundance")
      humann_100bp_shreds <- add_column(humann_100bp_shreds, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      pathabundance <- read_tsv(paste0("data/humann_wnanolyse/shredded_100bp/", filename), col_names = TRUE)
      colnames(pathabundance) <- c("Pathway", "Relative Abundance")
      pathabundance <- add_column(pathabundance, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_100bp_shreds <- rbind(humann_100bp_shreds, pathabundance)
    }
  }
}

humann_500bp_shreds <- data.frame()

for (filename in list.files("data/humann_wnanolyse/shredded_500bp/")) {
  if (grepl("pathabundance", filename)) {
    if (length(humann_500bp_shreds) == 0) {
      humann_500bp_shreds <- read_tsv(paste0("data/humann_wnanolyse/shredded_500bp/", filename), col_names = TRUE)
      colnames(humann_500bp_shreds) <- c("Pathway", "Relative Abundance")
      humann_500bp_shreds <- add_column(humann_500bp_shreds, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      pathabundance <- read_tsv(paste0("data/humann_wnanolyse/shredded_500bp/", filename), col_names = TRUE)
      colnames(pathabundance) <- c("Pathway", "Relative Abundance")
      pathabundance <- add_column(pathabundance, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_500bp_shreds <- rbind(humann_500bp_shreds, pathabundance)
    }
  }
}

humann_1kbp_shreds <- data.frame()

for (filename in list.files("data/humann/renormalized/shredded_1kbp")) {
  if (grepl("pathabundance", filename)) {
    if (length(humann_1kbp_shreds) == 0) {
      humann_1kbp_shreds <- read_tsv(paste0("data/humann/renormalized/shredded_1kbp/", filename), col_names = TRUE)
      colnames(humann_1kbp_shreds) <- c("Pathway", "Relative Abundance")
      humann_1kbp_shreds <- add_column(humann_1kbp_shreds, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      pathabundance <- read_tsv(paste0("data/humann/renormalized/shredded_1kbp/", filename), col_names = TRUE)
      colnames(pathabundance) <- c("Pathway", "Relative Abundance")
      pathabundance <- add_column(pathabundance, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_1kbp_shreds <- rbind(humann_1kbp_shreds, pathabundance)
    }
  }
}

humann_prodigal_community <- humann_prodigal[!grepl("|", humann_prodigal$Pathway, fixed = TRUE), ]
humann_100bp_shreds_community <- humann_100bp_shreds[!grepl("|", humann_100bp_shreds$Pathway, fixed = TRUE), ]
humann_500bp_shreds_community <- humann_500bp_shreds[!grepl("|", humann_500bp_shreds$Pathway, fixed = TRUE), ]
humann_1kbp_shreds_community <- humann_1kbp_shreds[!grepl("|", humann_1kbp_shreds$Pathway, fixed = TRUE), ]

```

```{r get_metacyc_metadata}

metacyc_metadata <- read_tsv("MetaCyc_pathway_metadata.txt", col_names = TRUE)
names(metacyc_metadata)[names(metacyc_metadata) == "Pathways"] <- "Pathway"

humann_prodigal_community_with_metadata <- humann_prodigal_community %>%
  add_column(PathwayDescription = str_trim(sapply(strsplit(humann_prodigal_community$Pathway, ":", fixed=TRUE), '[', 2))) %>%
  mutate(Pathway = sapply(strsplit(humann_prodigal_community$Pathway, ":", fixed=TRUE), '[', 1)) %>% 
  left_join(metacyc_metadata, by = "Pathway") 

humann_100bp_shreds_community_with_metadata <- humann_100bp_shreds_community %>%
  add_column(PathwayDescription = str_trim(sapply(strsplit(humann_100bp_shreds_community$Pathway, ":", fixed=TRUE), '[', 2))) %>%
  mutate(Pathway = sapply(strsplit(humann_100bp_shreds_community$Pathway, ":", fixed=TRUE), '[', 1)) %>% 
  left_join(metacyc_metadata, by = "Pathway") 

humann_500bp_shreds_community_with_metadata <- humann_500bp_shreds_community %>%
  add_column(PathwayDescription = str_trim(sapply(strsplit(humann_500bp_shreds_community$Pathway, ":", fixed=TRUE), '[', 2))) %>%
  mutate(Pathway = sapply(strsplit(humann_500bp_shreds_community$Pathway, ":", fixed=TRUE), '[', 1)) %>% 
  left_join(metacyc_metadata, by = "Pathway") 

humann_1kbp_shreds_community_with_metadata <- humann_1kbp_shreds_community %>%
  add_column(PathwayDescription = str_trim(sapply(strsplit(humann_1kbp_shreds_community$Pathway, ":", fixed=TRUE), '[', 2))) %>%
  mutate(Pathway = sapply(strsplit(humann_1kbp_shreds_community$Pathway, ":", fixed=TRUE), '[', 1)) %>% 
  left_join(metacyc_metadata, by = "Pathway") 

```

```{r get_genefamilies_files, results = 'hide'}

humann_prodigal_genefamilies <- data.frame()

for (filename in list.files("data/humann/renormalized/prodigal/")) {
  if (grepl("genefamilies", filename)) {
    if (length(humann_prodigal_genefamilies) == 0) {
      humann_prodigal_genefamilies <- read_tsv(paste0("data/humann/renormalized/prodigal/", filename), col_names = TRUE)
      colnames(humann_prodigal_genefamilies) <-  c("Gene Family", "RPKs")
      humann_prodigal_genefamilies <- add_column(humann_prodigal_genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      genefamilies <- read_tsv(paste0("data/humann/renormalized/prodigal/", filename), col_names = TRUE)
      colnames(genefamilies) <- c("Gene Family", "RPKs")
      genefamilies <- add_column(genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_prodigal_genefamilies <- rbind(humann_prodigal_genefamilies, genefamilies)
    }
  }
}

humann_100bp_shreds_genefamilies <- data.frame()

for (filename in list.files("data/humann_wnanolyse/shredded_100bp/")) {
  if (grepl("genefamilies", filename)) {
    if (length(humann_100bp_shreds_genefamilies) == 0) {
      humann_100bp_shreds_genefamilies <- read_tsv(paste0("data/humann_wnanolyse/shredded_100bp/", filename), col_names = TRUE)
      colnames(humann_100bp_shreds_genefamilies) <-  c("Gene Family", "RPKs")
      humann_100bp_shreds_genefamilies <- add_column(humann_100bp_shreds_genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      genefamilies <- read_tsv(paste0("data/humann_wnanolyse/shredded_100bp/", filename), col_names = TRUE)
      colnames(genefamilies) <- c("Gene Family", "RPKs")
      genefamilies <- add_column(genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_100bp_shreds_genefamilies <- rbind(humann_100bp_shreds_genefamilies, genefamilies)
    }
  }
}

humann_500bp_shreds_genefamilies <- data.frame()

for (filename in list.files("data/humann_wnanolyse/shredded_500bp/")) {
  if (grepl("genefamilies", filename)) {
    if (length(humann_500bp_shreds_genefamilies) == 0) {
      humann_500bp_shreds_genefamilies <- read_tsv(paste0("data/humann_wnanolyse/shredded_500bp/", filename), col_names = TRUE)
      colnames(humann_500bp_shreds_genefamilies) <-  c("Gene Family", "RPKs")
      humann_500bp_shreds_genefamilies <- add_column(humann_500bp_shreds_genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      genefamilies <- read_tsv(paste0("data/humann_wnanolyse/shredded_500bp/", filename), col_names = TRUE)
      colnames(genefamilies) <- c("Gene Family", "RPKs")
      genefamilies <- add_column(genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_500bp_shreds_genefamilies <- rbind(humann_500bp_shreds_genefamilies, genefamilies)
    }
  }
}


humann_1kbp_shreds_genefamilies <- data.frame()

for (filename in list.files("data/humann/renormalized/shredded_1kbp")) {
  if (grepl("genefamilies", filename)) {
    if (length(humann_1kbp_shreds_genefamilies) == 0) {
      humann_1kbp_shreds_genefamilies <- read_tsv(paste0("data/humann/renormalized/shredded_1kbp/", filename), col_names = TRUE)
      colnames(humann_1kbp_shreds_genefamilies) <-  c("Gene Family", "RPKs")
      humann_1kbp_shreds_genefamilies <- add_column(humann_1kbp_shreds_genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
    } else {
      genefamilies <- read_tsv(paste0("data/humann/renormalized/shredded_1kbp/", filename), col_names = TRUE)
      colnames(genefamilies) <- c("Gene Family", "RPKs")
      genefamilies <- add_column(genefamilies, SampleName = str_extract(filename, "[R]+[0-9]+"))
      
      humann_1kbp_shreds_genefamilies <- rbind(humann_1kbp_shreds_genefamilies, genefamilies)
    }
  }
}

humann_prodigal_genefamilies_notaxa <- humann_prodigal_genefamilies[!grepl("|", humann_prodigal_genefamilies$`Gene Family`, fixed = TRUE), ]
humann_100bp_shreds_genefamilies_notaxa <- humann_100bp_shreds_genefamilies[!grepl("|", humann_100bp_shreds_genefamilies$`Gene Family`, fixed = TRUE), ]
humann_500bp_shreds_genefamilies_notaxa <- humann_500bp_shreds_genefamilies[!grepl("|", humann_500bp_shreds_genefamilies$`Gene Family`, fixed = TRUE), ]
humann_1kbp_shreds_genefamilies_notaxa <- humann_1kbp_shreds_genefamilies[!grepl("|", humann_1kbp_shreds_genefamilies$`Gene Family`, fixed = TRUE), ]

```


```{r heatmap_of_community_pathways}

humann_prodigal_community_pathways_with_metadata <- humann_prodigal_community_with_metadata[str_trim(humann_prodigal_community_with_metadata$Pathway) != "UNMAPPED" & str_trim(humann_prodigal_community_with_metadata$Pathway) != "UNINTEGRATED", ]

humann_prodigal_community_pathways_with_metadata <- humann_prodigal_community_pathways_with_metadata[order(humann_prodigal_community_pathways_with_metadata$`Ontology - pathway type`, humann_prodigal_community_pathways_with_metadata$`Ontology - direct parents of entity`, humann_prodigal_community_pathways_with_metadata$`PathwayDescription`), ]

#community_pathway_heatmap <- ggplot(humann_prodigal_community_pathways_with_metadata, aes(x = SampleName, y = factor(PathwayDescription, levels = unique(humann_prodigal_community_pathways_with_metadata$`PathwayDescription`)), fill = log(`Relative Abundance`))) + 
#  geom_tile(colour = "#00000000", show.legend = FALSE) + 
#  theme(
#    panel.background = element_rect(fill = '#fff'),
#    panel.grid.major.y = element_line(colour="#00000000"),
#    panel.grid.major.x = element_line(colour="#00000011"),
#    plot.background = element_rect(fill = '#fff'),
#    legend.background = element_rect(fill = '#fff')
#  )

community_pathway_heatmap <- ggplot(humann_prodigal_community_pathways_with_metadata, aes(x = SampleName, y = factor(`Ontology - pathway type`), fill = log(`Relative Abundance`))) + 
  geom_tile(colour = "#00000000", show.legend = FALSE) + 
  theme(
    panel.background = element_rect(fill = '#fff'),
    panel.grid.major.y = element_line(colour="#00000000"),
    panel.grid.major.x = element_line(colour="#00000011"),
    plot.background = element_rect(fill = '#fff'),
    legend.background = element_rect(fill = '#fff')
  )

ggsave("graphs/humann/community_pathway_heatmap_prodigal.png", community_pathway_heatmap, units = "px", height = 4000, width = 2700, limitsize = FALSE)
community_pathway_heatmap

humann_1kbp_shreds_community_pathways_with_metadata <- humann_1kbp_shreds_community_with_metadata[str_trim(humann_1kbp_shreds_community_with_metadata$Pathway) != "UNMAPPED" & str_trim(humann_1kbp_shreds_community_with_metadata$Pathway) != "UNINTEGRATED", ]

humann_1kbp_shreds_community_pathways_with_metadata <- humann_1kbp_shreds_community_pathways_with_metadata[order(humann_1kbp_shreds_community_pathways_with_metadata$`Ontology - pathway type`, humann_1kbp_shreds_community_pathways_with_metadata$`Ontology - direct parents of entity`, humann_1kbp_shreds_community_pathways_with_metadata$`PathwayDescription`), ]

community_pathway_heatmap <- ggplot(humann_1kbp_shreds_community_pathways_with_metadata, aes(x = SampleName, y = factor(PathwayDescription, levels = unique(humann_1kbp_shreds_community_pathways_with_metadata$`PathwayDescription`)), fill = log(`Relative Abundance`))) + 
  geom_tile(colour = "#00000000", show.legend = FALSE) + 
  theme(
    panel.background = element_rect(fill = '#fff'),
    panel.grid.major.y = element_line(colour="#00000000"),
    panel.grid.major.x = element_line(colour="#00000011"),
    plot.background = element_rect(fill = '#fff'),
    legend.background = element_rect(fill = '#fff')
  )

ggsave("graphs/humann/community_pathway_heatmap_1kbp_shreds.png", community_pathway_heatmap, units = "px", height = 17000, width = 2700, limitsize = FALSE)
community_pathway_heatmap

humann_100bp_shreds_community_pathways_with_metadata <- humann_100bp_shreds_community_with_metadata[str_trim(humann_100bp_shreds_community_with_metadata$Pathway) != "UNMAPPED" & str_trim(humann_100bp_shreds_community_with_metadata$Pathway) != "UNINTEGRATED", ]

humann_100bp_shreds_community_pathways_with_metadata <- humann_100bp_shreds_community_pathways_with_metadata[order(humann_100bp_shreds_community_pathways_with_metadata$`Ontology - pathway type`, humann_100bp_shreds_community_pathways_with_metadata$`Ontology - direct parents of entity`, humann_100bp_shreds_community_pathways_with_metadata$`PathwayDescription`), ]

community_pathway_heatmap <- ggplot(humann_100bp_shreds_community_pathways_with_metadata, aes(x = SampleName, y = factor(PathwayDescription, levels = unique(humann_100bp_shreds_community_pathways_with_metadata$`PathwayDescription`)), fill = log(`Relative Abundance`))) + 
  geom_tile(colour = "#00000000", show.legend = FALSE) + 
  theme(
    panel.background = element_rect(fill = '#fff'),
    panel.grid.major.y = element_line(colour="#00000000"),
    panel.grid.major.x = element_line(colour="#00000011"),
    plot.background = element_rect(fill = '#fff'),
    legend.background = element_rect(fill = '#fff')
  )

ggsave("graphs/humann/community_pathway_heatmap_100bp_shreds.png", community_pathway_heatmap, units = "px", height = 17000, width = 2700, limitsize = FALSE)
community_pathway_heatmap

#for (pathway in humann_prodigal_community_pathways_with_metadata$PathwayDescription) {
#  graph <- ggplot(na.omit(humann_prodigal_community_pathways_with_metadata[humann_prodigal_community_pathways_with_metadata$`PathwayDescription` == pathway & !is.na(humann_prodigal_community_pathways_with_metadata$PathwayDescription), ]), aes(x = SampleName, y = log(`Relative Abundance`))) + 
#    geom_bar(stat = "identity", show.legend = FALSE) + 
#    ggtitle(pathway)
  
#  ggsave(paste0("graphs/humann/breakdown/", str_replace_all(string = pathway, pattern = "/", replacement = ""), ".png"), graph, units = "px", height = 2000, width = 2750)
#}

```

```{r pheatmap_of_pathways}

humann_prodigal_community_wide <- humann_prodigal_community %>%
  pivot_wider(
    names_from = SampleName,
    values_from = `Relative Abundance`,
    values_fill = 0,
    values_fn = sum
  )

humann_prodigal_pathway_names <- humann_prodigal_community_wide$Pathway
humann_prodigal_community_wide <- humann_prodigal_community_wide[, -c(1)]
rownames(humann_prodigal_community_wide) <- humann_prodigal_pathway_names

humann_prodigal_community_wide <- log(humann_prodigal_community_wide + 1)

pheatmap(as.matrix(humann_prodigal_community_wide), 
         filename = "graphs/humann/dendrogram_heatmap_prodigal.png",
         cellwidth = 45,
         cellheight = 15
         )

```

```{r barchart_of_unmapped}

unmapped_unintegrated_humann <- rbind(
  humann_prodigal_community[humann_prodigal_community$Pathway == "UNMAPPED" | humann_prodigal_community$Pathway == "UNINTEGRATED", ] %>% add_column(Input = "Prodigal ORFs"),
  humann_1kbp_shreds_community[humann_1kbp_shreds_community$Pathway == "UNMAPPED" | humann_1kbp_shreds_community$Pathway == "UNINTEGRATED", ] %>% add_column(Input = "1kbp Shreds"),
  humann_100bp_shreds_community[humann_100bp_shreds_community$Pathway == "UNMAPPED" | humann_100bp_shreds_community$Pathway == "UNINTEGRATED", ] %>% add_column(Input = "100bp Shreds"),
  humann_500bp_shreds_community[humann_500bp_shreds_community$Pathway == "UNMAPPED" | humann_500bp_shreds_community$Pathway == "UNINTEGRATED", ] %>% add_column(Input = "500bp Shreds")
)

unmapped_reads <- ggplot(unmapped_unintegrated_humann[unmapped_unintegrated_humann$Pathway == "UNMAPPED", ], aes(x = SampleName, y = `Relative Abundance`, fill = Input)) + 
  geom_bar(stat = "identity", position = position_dodge()) + 
  ggtitle("Abundance of Unmapped Reads (reads that do not map to any genes)")

ggsave("graphs/humann/unmapped_reads.png", unmapped_reads, units = "px", width = 3000, height = 2500)
unmapped_reads

unintegrated_genes <- ggplot(unmapped_unintegrated_humann[unmapped_unintegrated_humann$Pathway == "UNINTEGRATED", ], aes(x = SampleName, y = `Relative Abundance`, fill = Input)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  ggtitle("Abundance of Unintegrated Genes (genes that do not belong to a MetaCyc pathway definition)") 

ggsave("graphs/humann/unintegrated_genes.png", unintegrated_genes, units = "px", width = 3000, height = 2500)
unintegrated_genes

```


```{r ordination}

humann_prodigal_community_for_ordination <- humann_prodigal_community %>%
  pivot_wider(
    names_from = SampleName,
    values_from = `Relative Abundance`,
    values_fill = 0,
    values_fn = sum
  )

humann_prodigal_mds <- metaMDS(as.data.frame(t(humann_prodigal_community_for_ordination[, -c(1)])))

humann_100bp_shreds_community_for_ordination <- humann_100bp_shreds_community %>%
  pivot_wider(
    names_from = SampleName,
    values_from = `Relative Abundance`,
    values_fill = 0,
    values_fn = sum
  )

humann_100bp_shreds_mds <- metaMDS(as.data.frame(t(humann_100bp_shreds_community_for_ordination[, -c(1)])))

humann_500bp_shreds_community_for_ordination <- humann_500bp_shreds_community %>%
  pivot_wider(
    names_from = SampleName,
    values_from = `Relative Abundance`,
    values_fill = 0,
    values_fn = sum
  )

humann_500bp_shreds_mds <- metaMDS(as.data.frame(t(humann_500bp_shreds_community_for_ordination[, -c(1)])))

humann_1kbp_shreds_community_for_ordination <- humann_1kbp_shreds_community %>%
  pivot_wider(
    names_from = SampleName,
    values_from = `Relative Abundance`,
    values_fill = 0,
    values_fn = sum
  )

humann_1kbp_shreds_mds <- metaMDS(as.data.frame(t(humann_1kbp_shreds_community_for_ordination[, -c(1)])))


ggplot(as.data.frame(humann_prodigal_mds[["points"]]), aes(x = MDS1, y = MDS2, label = rownames(as.data.frame(humann_prodigal_mds[["points"]])))) +
  geom_point() + 
  geom_text()

ggplot(as.data.frame(humann_100bp_shreds_mds[["points"]]), aes(x = MDS1, y = MDS2, label = rownames(as.data.frame(humann_100bp_shreds_mds[["points"]])))) +
  geom_point() + 
  geom_text()

ggplot(as.data.frame(humann_500bp_shreds_mds[["points"]]), aes(x = MDS1, y = MDS2, label = rownames(as.data.frame(humann_500bp_shreds_mds[["points"]])))) +
  geom_point() + 
  geom_text()

ggplot(as.data.frame(humann_1kbp_shreds_mds[["points"]]), aes(x = MDS1, y = MDS2, label = rownames(as.data.frame(humann_1kbp_shreds_mds[["points"]])))) +
  geom_point() + 
  geom_text()

```


```{r acetate_pathways}

acetate_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY66-21", "PWY66-161", "PWY66-162", "PWY-7387", "PWY-5641", "TOLUENE-DEG-DIOL-PWY", "TOLUENE-DEG-2-OH-PWY", "PWY-5754", "PWY-6431", "PWY-5665", "GLUAMCAT-PWY", "PWY-6906", "PWY0-1261", "PWY-7000", "PWY-7014", "PWY-7022", "PWY-8202", "PWY66-378", "PWY-5022", "PWY-5677", "PWY-7077", "PWY-7395", "PWY8J2-25", "PWY-8418", "PWY-7174", "PWY-8132", "PWY-5867", "PWY-5882", "PWY-7268", "PWY-5768", "P162-PWY", "PWY-8190", "PWYI-14", "PWY-8245", "PWY-5794", "PWY-6060", "PWY-7545", "PWY-7544", "PWY-4961", "PWY-8337", "PWY-5643", "PWY-7521", "PWY-7002", "PWY-6672", "PWY-8071", "PWY-5301", "PWY-8293", "PWY-7599", "P482-PWY", "PWY8J2-1", "PWY-8200", "PWY-6444", "PWY-7118", "PWY-6855", "PWY0-1309", "PWY-6038", "P2-PWY", "PWY-7376", "PWY-4741", "PWY-7401", "PWY-7274", "PWY-8453", "PWY-7712", "PWY-6056", "PWY-7855", "PWY-5883", "PWY-8408", "PWY-5708", "PWY-5859", "PWY-5835", "PWY-804", "PWY-7552", "PWY-6558", "PWY-8087", "PWY-5154", "CYSTSYN-PWY", "PWY-I9", "PWY-7870", "PWY-5075", "PWY-2941", "LYSDEGII-PWY", "GLUTORN-PWY", "PWY-8530", "PWY-6955", "PWY2B4Q-4", "NAGLIPASYN-PWY", "PWY-8245", "PWY-8073", "PWY2G6Z-2", "PWY-8283", "PWY-5967", "PWY-6399", "PWY-4985", "PWY-5270", "PWY1G-0", "PWY-7016", "PWY-8506", "PWY-7713", "PWY-7138", "P342-PWY", "PWY-6699", "PWY-7018", "P641-PWY", "PWY-7769", "PWY-6322", "P483-PWY", "PWY0-1609", "PWY-6464", "PWY-7774", "PWY-7775", "PWY-5929", "PWY-0", "PWY-7906", "PWY-6936", "SOPHOROSYLOXYDOCOSANOATE-DEG-PWY", "PWY-7730", "PWY-7403", "PWY-7821", "PWY-8229", "PWY-5955", "PWY-5292", "PWY-5499", "PWY-8384", "PWY-5021")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-5022", "PWY-5676", "P3-PWY", "P162-PWY", "PWY-8190", "PWY-5677", "P2-PWY", "P3-PWY", "PWY-6060"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-8086", "PWY0-1312", "P161-PWY", "P124-PWY", "PWY0-1477", "P3-PWY", "PWY-8015", "P163-PWY", "PWY-8377", "METH-ACETATE-PWY", "FERMENTATION-PWY", "PWY-8480", "P164-PWY", "PWY-5497", "PWY-5482", "PWY-5485", "PWY-8303", "PWY4LZ-257", "PWY-6672", "PWY-8328", "PWY0-1313", "PWY-7118", "PWY66-21", "PWY66-161", "PWY66-162", "PWY-8303", "PWY-5536", "PWY-7384", "PWY-5677", "PWY-7254", "PWY-5535", "PWY-8305", "PWY-5483", "PWY-5494", "PWY-5109", "ACETOACETATE-DEG-PWY", "PWY-6588", "PWY-7541", "PWY-6855", "PWY-5087", "PWY-5344", "PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% acetate_pathways$Pathway) %>%
  left_join(acetate_pathways, by = "Pathway", multiple = "last") %>%
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Acetate Pathways")) %>%
  
  ggsave("graphs/humann/specific/SCFAs/acetate.png", ., units = "px", width = 2400, height = 2200)
  

```


```{r propanoate_pathways}

propanoate_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("2OXOBUTYRATECAT-PWY", "PWY-7554", "PWY-5736", "PWY-5055", "PWY-5148", "PWY-2724", "PWY-2501", "PWY-6803", "LIPASYN-PWY", "PWY-7277", "PWY3DJ-11281", "PWY-8052", "PWY-5142", "PWY-8051", "PWY-6483", "PWY-7783", "PWY-6857", "PWY3DJ-11470", "PWY-6861", "LIPAS-PWY", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-3941", "PWY0-42", "PWY-5747", "PWY-5104", "FA0-PWY", "PWY-5136", "PWY66-391", "PWY-7288", "PWY-2724", "PWY-2501", "PWY-7007", "PWY-7671", "PWY-7694"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-8086", "PWY-7384", "PWY0-43", "P108-PWY", "PWY-7013", "PWY-5437", "PWY-5494", "PWY-5109", "PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% propanoate_pathways$Pathway) %>%
  left_join(propanoate_pathways, by = "Pathway", multiple = "last") %>%
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Propanoate Pathways")) %>%
  
  ggsave("graphs/humann/specific/SCFAs/propanoate.png", ., units = "px", width = 2400, height = 1400)
  

```


```{r butanoate_pathways}

butanoate_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-8190", "PWY-5022", "GLUDEG-II-PWY", "CENTFERM-PWY", "PWY-5676", "P162-PWY", "PWY-5677")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("FAO-PWY", "PWY-5136", "PWY66-391", "PWY-7288", "PWY-2724", "PWY-2501", "PWY-7007", "PWY-7671", "PWY-7694"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("P163-PWY", "PWY-6588", "CENTFERM-PWY", "PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% butanoate_pathways$Pathway) %>%
  left_join(butanoate_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Butanoate Pathways")) %>%
  
  ggsave("graphs/humann/specific/SCFAs/butanoate.png", ., units = "px", width = 2400, height = 1400)
  

```


```{r pentanoate_pathways}

pentanoate_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-5148", "PWY-2724", "PWY-2501", "PWY-6803", "LIPASYN-PWY", "PWY-7277", "PWY3DJ-11281", "PWY-8052", "PWY-5142", "PWY-8051", "PWY-6483", "PWY-7783", "PWY-6857", "PWY3DJ-11470", "PWY-6861", "LIPAS-PWY", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("FAO-PWY", "PWY-5136", "PWY66-391", "PWY-7288", "PWY-2724", "PWY-2501", "PWY-7007", "PWY-7671", "PWY-7694"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% pentanoate_pathways$Pathway) %>%
  left_join(pentanoate_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Pentanoate Pathways")) %>%
  
  ggsave("graphs/humann/specific/SCFAs/pentanoate.png", ., units = "px", width = 2400, height = 1400)
  

```


```{r hexanoate_pathways}

hexanoate_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-5148", "PWY-2724", "PWY-2501", "PWY-6803", "LIPASYN-PWY", "PWY-7277", "PWY3DJ-11281", "PWY-8052", "PWY-5142", "PWY-8051", "PWY-8053", "PWY-6483", "PWY-7783", "PWY-6857", "PWY3DJ-11470", "PWY-6861", "LIPAS-PWY", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-7641", "PWY-8360", "PWY-5140", "FAO-PWY", "PWY-5136", "PWY66-391", "PWY-7288", "PWY-2724", "PWY-2501", "PWY-7007", "PWY-7671", "PWY-7694"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% hexanoate_pathways$Pathway) %>%
  left_join(hexanoate_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Hexanoate Pathways")) %>%
  
  ggsave("graphs/humann/specific/SCFAs/hexanoate.png", ., units = "px", width = 2400, height = 1400)
  

```


```{r alanine_pathways}

alanine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-6891", "PWY-7888", "PWY-7889", "PWY-7891", "PWY-7904", "PWYDQC-4", "PWY-7770", "PWY0-1021", "PWY-8452", "TRPCAT-PWY", "PWY-6309", "PWY-5651", "PWY-7907", "PWY-7717", "PWY-7765", "PWY-8164", "PWY-8165", "PWY-1822", "PWY-5736", "PWY-5468", "PWY-5963", "PWY-6823", "PWY0-1546", "PWY-8561", "PWY-6892", "PWY-6891", "PWY8J2-27", "PWY-7892", "PWY-7904", "PWY-8566", "PWY-7250", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-7907", "PWY-8117", "PWY-6495", "PWY-8528", "PWY-8527", "PWY-7769", "PWY-6322", "PWY-8381", "PWY-6519", "PWY-7147", "PWY-8203", "PWY-6387", "PWY-6386", "PWY-7953", "PWY-8528", "PWY-8527", "PWY-7769", "PWY-6322", "PWY-7907", "PWY-7543", "PWY-6578", "PWY-8293", "PWY-8494", "PWY-8492", "PWY-8496", "PWY-8361", "PWY-8489", "PWY-7626", "PWY-8443", "PWY-6682", "PWY-7735", "PWY-6495", "PWY-7542", "PWY-6219", "PWY-5254", "PWY-8495", "PWY-8527", "PWY-6322", "PWY-7351", "PWY-7671", "PWY-8381", "TRNA-CHARGING-PWY", "PWY-7694", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-7383", "PWY-7115", "PWY-7117", "ALANINE-SYN2-PWY", "ALACAT2-PWY", "ALANINE-DEG3-PWY", "PWY-8189", "PWY-8188", "PWY-8072", "PWY-7383", "PWY-8040", "PWY-8443", "ALADEG-PWY", "PWY-6839", "PHOSPHONOTASE-PWY", "PWY-6832", "PWY-8529", "PWY-7275", "PWY-5079", "PWY-3941", "PWY-1781", "PWY-7115", "PWY-7117", "PWY-8493", "PWY3O-4108", "PWY-5748", "PWY-6473", "PWY-5710", "PWY-7880", "GLYSYN-ALA-PWY", "PWY-5826", "PWY-7387", "ALANINE-VALINESYN-PWY", "PWY1-2", "PWY-5742", "PWY-5031", "PWY-7275", "PWY-8493", "PWY-5324", "PWY-8011", "PWY-3", "PWY-6456", "PWY-5940", "PWY-1263", "PWY-5499", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% alanine_pathways$Pathway) %>%
  left_join(alanine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Alanine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/alanine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r arginine_pathways}

arginine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-7052", "PWY-6422", "NOPALINEDEG-PWY", "OCTOPINEDEG-PWY", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY0-1299", "PWY0-823", "ARGDEG-III-PWY", "PWY-40", "PWY-43", "PWY-6834", "PWY2PN3-14", "GLYCGREAT-PWY", "PWY-8045", "PWY-7693", "PWY-8506", "ARGDEGRAD-PWY", "PWY-8187", "PWY-6344", "PWY-8492", "PWY-8496", "PWY-6853", "PWY-7126", "ARGDEG-V-PWY", "PWY-8532", "PWY-4981", "PWY2PN3-13", "PWY-6845", "PWY-4983", "PWY-7860", "PWY-8531", "PWY-8450", "PWY-7351", "PWY-8451", "PWY-7570", "PWY-5679", "PWY-7052", "PWY-8045", "PWY-7274", "PWY-6853", "PWY-7770", "PWY-8529", "AST-PWY", "ARGDEG-IV-PWY", "PWY-8498", "PWY-6845", "PWY-7860", "PWY-7797", "PWY-7600", "PWY-6409", "PWY-7510", "PWY-5940", "TRNA-CHARGING-PWY", "PWY-7987", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-6922", "ARGASEDEG-PWY", "ARG-PRO-PWY", "ARG-GLU-PWY", "CITRULBIO-PWY", "PWY-46", "PWY-4984", "ARGSYN-PWY", "ARGSYNBSUB-PWY", "PWY-5154", "PWY-7400", "PWY-4983", "PWY2PN3-13", "PWY-6511", "PWY-5024", "PWY-5742", "PWY-7523", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% arginine_pathways$Pathway) %>%
  left_join(arginine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Arginine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/arginine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r asparagine_pathways}

asparagine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("ASPSYNII-PWY", "ASPARAGINE-BIOSYNTHESIS", "ASPARAGINESYN-PWY", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("ASPARAGINE-DEG1-PWY", "ASPASN-PWY", "PWY-8402", "PWY-8117", "TRNA-CHARGING-PWY", "PWY-7694", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7510"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-4002", "PWYQT-4450", "PWY-1186", "PWY-7119")))


(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% asparagine_pathways$Pathway) %>%
  left_join(asparagine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Asparagine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/asparagine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r aspartate_pathways}

aspartate_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-7855", "PWY-8419", "ASPARAGINE-DEG1-PWY", "ASPASN-PWY", "PWY-8402", "PWY-8454", "ASPSYNII-PWY", "PWY-7052", "PWY-1962", "PWY-5784", "ASPARAGINE-DEG1-PWY-1", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-6160", "PWY-8296", "PWY-8088", "P101-PWY", "PWY-7153", "HOMOSERSYN-PWY", "DAPLYSINESYN-PWY", "PWY-2941", "PWY-2942", "PWY-5097", "PWY-7977", "PWY-6562", "PWY-8179", "PWY-6559", "PWY-1962", "PWY-1981", "PWY-2021", "PWY-5797", "PWY-5811", "PWY-6219", "PWY-5784", "ARGSYN-PWY", "ARGSYNBSUB-PWY", "PWY-5154", "PWY-7400", "PWY-4983", "PWY2PN3-13", "PWY-4984", "PWY-6123", "PWY-6124", "PWY-7234", "PYRIDNUCSYN-PWY", "PWY-5316", "PWY-7342", "PWY-5686", "PWY-7790", "PWY-7791", "PWY-5155", "PWY-8526", "PWY-7219", "PWY-5", "PWY-7052", "PWY-8289", "ASPARAGINE-BIOSYNTHESIS", "ASPARAGINESYN-PWY", "PWY490-4", "PWY-8498", "PWY-8352", "PWY-8277", "PWY-8295", "PWY-8563", "PWY-6148", "PWY-6720", "TRNA-CHARGING-PWY", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-7383", "PWY-7115", "PWY-7117", "ASPARTATESYN-PWY", "ASPARTATE-DEG1-PWY", "GLUTDEG-PWY", "MALATE-ASPARTATE-SHUTTLE-PWY", "PWY-8560", "PWY-8291", "PWY-8294", "PWY-8419", "GLUTDEG-PWY", "ASPASN-PWY", "PWY-3462", "PWY-3461", "PWY-6120", "PWY-7115", "PWY-7117", "PWY-6511", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% aspartate_pathways$Pathway) %>%
  left_join(aspartate_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Aspartate Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/aspartate.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r cysteine_pathways}

cysteine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-801", "HOMOCYSDEGR-PWY", "PWY-I9", "PWY-4041", "PWY-7559", "PWY8J2-25", "PWY-8418", "PWY-8010", "PWY-8009", "PWY-6577", "CYSTSYN-PWY", "PWY-6308", "PWY-7289", "PWY-7870", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-8539", "PWY-7986", "PWY-8117", "PWY-8450", "PWY-6408", "PWY-7737", "PWY-6891", "PWY-7888", "PWY-7889", "PWY-7891", "PWY-7904", "PWY-7986", "PWY-8358", "PWY-8343", "PWY-7255", "GLUTATHIONESYN-PWY", "PWY-6840", "PWY-8539", "PWY-8540", "PWY-6408", "PWY-7986", "PWY-8361", "PWY-8360", "COA-PWY", "PWY-8342", "PWY-7851", "PWY-7850", "PWY-801", "HOMOSER-METSYN-PWY", "PWY66-426", "LCYSDEG-PWY", "PWY0-1021", "PWY-8452", "CYSTEINE-DEG-PWY", "PWY-5331", "PWY-8164", "PWY8J2-25", "PWY-8523", "PWY-8397", "PWY8J2-1", "PWY-8165", "PWY-7735", "PWY-7550", "PWY-7913", "PWY-7690", "PWY66-426", "PWYQT-4476", "PWY-5629", "PWY-8540", "LCYSDEG-PWY", "PWY-702", "PWY-5963", "PWY-6823", "PWY1G-0", "PWY-8561", "PWY-7917", "PWY-6408", "PWY-8359", "PWY-6892", "PWY-6891", "PWY-7737", "TRNA-CHARGING-PWY", "PWY8J2-27", "PWY-7892", "PWY-7904", "PWY-6407", "PWY-8566", "PWY-7250", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-801", "HOMOCYSDEGR-PWY", "PWY-I9", "PWY-4041", "PWY-7559", "PWY8J2-25", "PWY-8418", "PWY-8010", "PWY-8009", "PWY-6577", "CYSTSYN-PWY", "PWY-6308", "PWY-7289", "PWY-7870", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% cysteine_pathways$Pathway) %>%
  left_join(cysteine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Cysteine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/cysteine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r glutamate_pathways}

glutamate_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PYRIDNUCSYN-PWY", "PWY-8352", "PWY-8277", "PWY-5653", "PWY-8511", "PWY-5381", "PYRIDNUCSAL-PWY", "PWY-7761", "PWY30-4107", "ARGSYN-PWY", "ARGSYNBSUB-PWY", "PWY-5154", "PWY-7400", "PWY2PN3-13", "PWY-5686", "PWY-7790", "PWY-7791", "AMMASSIM-PWY", "PWY-5921", "PWY490-4", "CITRULBIO-PWY", "GLUTSYN-PWY", "GLUTAMINDEG-PWY", "PWY-6984", "PWY-8346", "PWY-4341", "PWY-6549", "PWY-6749", "PWY-8013", "UDPNAGSYN-PWY", "UDPNACETYLGALSYN-PWY", "PWY-6661", "PWY-5958", "TRPSYN-PWY", "PWY-6121", "PWY-6122", "PWY-6277", "AMMASSIM-PWY", "GLUTSYN-PWY", "GLUTAMINEFUM-PWY", "PWY-6853", "ARGASEDEG-PWY", "PROUT-PWY", "PWY-7176", "PWY-7185", "PWY-7177", "BETA-ALA-DEGRADATION-I-PWY", "PWY-8120", "PWY-4041", "PWY-7942", "PWY-6543", "PWY-8032", "PWY-7861", "PWY66-425", "PWY-6963", "GLUGLNSYN-PWY", "AMMASSIM-PWY", "GLUTSYN-PWY", "PWY-8382", "PWY-5770", "PWY-4061", "PWY-6842", "PWY-5265", "PWY-6471", "PWY-5912", "PWY-7733", "PWY-8276", "PWY-7112", "PWY-7811", "PWY-7054", "PWY-8301", "PWY-7962", "PWY-5706", "PWY-6533", "PWY-8397", "CAMALEXIN-SYN", "PWY-7377", "PWY-7376", "PWY-8512", "PWY-8453", "PWY-7706", "PWY-7255", "PWY-5196", "PWY-8001", "PWY-7025", "PWYQT-4471", "PWYQT-4475", "PWY-1187", "PWYQT-4474", "PWY-2821", "PWTQT-4473", "PWYQT-4472", "PWY-601", "PWY-7901", "PWY-2161B", "PWY-5921", "PWY-7559", "PWY-6842", "PWY-7221", "PWYQT-4477", "PWY-5784", "PWY-5736", "AST-PWY", "ASPARAGINE-BIOSYNTHESIS", "PWY490-4", "HISTSYN-PWY", "HISDEG-PWY", "PWY-5028", "PWY-5030", "PWY-5103", "PWY-5075", "LYSINE-DEG1-PWY", "PWY-6309", "PWY-7614", "PWY-6965", "PWY0-1546", "P621-PWY", "PWY-5707", "PWY0-1221", "PWY-6409", "PWY-6466", "PWY-5297", "PWY-8229", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-6963", "PWY-6964", "AMMASSIM-PWY", "ARGSYNBSUB-PWY", "PWY-8291", "PWY-8294", "GLNSYN-PWY", "PWY-7706", "PWY-8008", "PWY-8381", "PWY-7694", "GLUDEG-I-PWY", "PWY-8346", "PWY-8543", "PWY0-1305", "PWY-6922", "CITRULBIO-PWY", "ARGININE-SYN4-PWY", "PROSYN-PWY", "PWY-7255", "GLUTATHIONESYN-PWY", "PWY-6840", "ARGSYNBSUB-PWY", "PWY-5154", "GLUTORN-PWY", "PWY-6219", "PWY-5784", "TRNA-CHARGING-PWY", "PWY-5188", "PWY-7907", "PWY-8441", "PWY-8505", "PWY-6533", "PWY-7019", "PWY-7719", "PWY-8083", "PWY-7315", "PWY-7814", "PWY-5199", "PWY-2161", "PWY-5740", "PWY-7025", "PWY-5921", "PWY-7693", "PWY-7072", "PWY-8367", "PWY-8158", "PWY-5736", "PWY-8080", "ARGSYNBSUB-PWY", "PWY-7400", "DAPLYSINESYN-PWY", "PWY-2941", "LYSINE-AMINOAD-PWY", "PWY-7531", "PWY-5254", "PWY-6965", "PWY-8383", "PWY-8043", "PWY-8439", "PWY0-1221", "PWY-6409", "PWY-7863", "PWY-8321", "PWY-8366", "PWY-8563", "PWY-6614", "PWY2DNV-11", "PWY-8456", "PWY-8273", "PWY-7953", "PWY-5818", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-3581", "PWY-5886", "PWY-5754", "PWY-7518", "TYRSYN", "TYRFUMCAT-PWY", "PWY-5151", "PWY3O-4108", "PWY-7514", "PWY-8016", "PWY-5048", "PWY-8173", "ILEUSYN-PWY", "PWY-5101", "PWY-5103", "PWY-5104", "PWY-5108", "ILEUDEG-PWY", "PWY-5078", "PWY-8184", "PWY-7383", "PWY-7115", "PWY-7117", "ASPARTATESYN-PWY", "ASPARTATE-DEG1-PWY", "GLUTDEG-PWY", "MALATE-ASPARTATE-SHUTTLE-PWY", "PWY-8560", "PWY-7383", "PWY-7115", "ALACAT2-PWY", "ALANINE-DEG3-PWY", "PWY-8189", "PWY-8188", "PWY-6535", "PWY-6537", "PWY-6536", "PWY-5022", "GLUDEG-I-PWY", "PWY-8346", "P181-PWY", "PWY-7126", "ALACAT2-PWY", "GLUTAMATE-DEG1-PWY", "P162-PWY", "PWY-8190", "PWY-6728", "PWY-6922", "ARGASEDEG-PWY", "ARG-PRO-PWY", "PWY-8187", "CITRULBIO-PWY", "ARGININE-SYN4-PWY", "PWY-3341", "LEUSYN-PWY", "LEU-DEG2-PWY", "PWY-5076", "PWY-7767", "PWY-8185", "PWY-8174", "PWY-8525", "PWY-7988", "P101-PWY", "PWY-7855", "PWY-6562", "PWY-6409", "PWY-761", "PHESYN", "ANAPHENOXI-PWY", "PWY-5079", "PWY-6318", "PWY-8014", "PWY-8565", "PWY-8175", "VALSYN-PWY", "VALDEG-PWY", "PWY-5057", "PWY-8183", "PWY-581", "TRPIAACAT-PWY", "TRPKYNCAT-PWY", "PWY-5081", "PWY-8017", "LYSINE-AMINOAD-PWY", "PWY-3081", "PWY66-425", "PWY-5283", "LYSINE-DEG1-PWY", "PWY0-461", "LYSDEGII-PWY", "PWY-5280", "PWY-6328", "PWY-6642", "PWY-6643", "PWY-6638", "PWY-6121", "PWY-6122", "PWY-6277", "PWY-7316", "PWY-6942", "PWY-8504", "GLUDEG-I-PWY", "GLUTAMATE-SYN2-PWY", "PWY-5766", "PWY-8225", "PWY2B4Q-2", "PWY-5739", "ARGSYNBSUB-PWY", "PWY-5154", "GLUTORN-PWY", "PWY-5087", "PWY-5103", "PWY-6728", "PWY-3462", "PWY-3461", "PWY-6120", "PWY-181", "PWY-8362", "PWY-8363", "PWY-6133", "PWY-5049", "PWY-5029", "HISTDEG-PWY", "PWY-6511", "PWY-5024", "PWY-7115", "PWY-7117", "PWY-8443", "PWY-8043", "PWY-7414", "PWY-7318", "PWY-7688", "PWY-6953", "PWY-7440", "PWY-7104", "PWY-7000", "PWY-7015", "PWY-8010", "SERSYN-PWY", "PWY0-461", "PWY-6328", "PWY-7467", "PWY-7842", "PWY-6387", "PWY-6386", "HYDROXYPRODEG-PWY", "PWY-6711", "PWY-8032", "PWY-7674", "PWY-6749", "PWY-6143", "PWY-8161", "PWY-6682", "PWY-6808", "PWY-6942", "PWY-8380", "PWY-5883", "PWY-7025", "PWY-6321", "PWY8J2-22", "PWY-7400", "AST-PWY", "CYSTEINE-DEG-PWY", "PWY-5329", "PWY-6334", "GLUTSYNIII-PWY", "HISTSYN-PWY", "PWY-3081", "PWY-5097", "LYSDEGII-PWY", "PWY-5298", "PWY-6309", "VALDEG-PWY", "PWY-6965", "PWY-7016", "PWY-7018", "PWY0-1338", "PUTDEG-PWY", "PYRIDOXSYN-PWY", "TAURINEDEG-PWY", "PWY-7090", "PWY-7028", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% glutamate_pathways$Pathway) %>%
  left_join(glutamate_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName, ncol = 6) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Glutamate Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/glutamate.png", ., units = "px", width = 3800, height = 2500)
  

```


```{r glutamine_pathways}

glutamine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-6963", "PWY-6964", "AMMASSIM-PWY", "ARGSYNBSUB-PWY", "PWY-8291", "PWY-8294", "GLNSYN-PWY", "PWY-8298", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PYRIDNUCSYN-PWY", "PWY-8352", "PWY-8277", "PWY-5653", "PWY-8511", "PWY-5381", "PYRIDNUCSAL-PWY", "PWY-7761", "PWY3O-4107", "ARGSYN-PWY", "ARGSYNBSUB-PWY", "PWY-5154", "PWY-7400", "PWY2PN3-13", "PWY-5686", "PWY-7790", "PWY-7791", "AMMASSIM-PWY", "PWY-5921", "PWY490-4", "CITRULBIO-PWY", "GLUTSYN-PWY", "GLUTAMINDEG-PWY", "PWY-6964", "PWY-8346", "PWY-4341", "PWY-6549", "PWY-6749", "PWY-8013", "UDPNAGSYN-PWY", "UDPNACETYLGALSYN-PWY", "PWY-8367", "PWY-7000", "PWY-7014", "PWY-7022", "PWY-6661", "PWY-5958", "TRPSYN-PWY", "PWY-6121", "PWY-6122", "PWY-6277", "AMMASSIM-PWY", "GLUTSYN-PWY", "GLUTAMINEFUM-PWY", "PWY-7176", "PWY-7185", "PWY-7177", "PWY-6543", "PWY-8032", "PWY-6963", "GLUGLNSYN-PWY", "PWY-8382", "PWY-5770", "PWY-5265", "PWY-6471", "PWY-8276", "PWY-7811", "PWY-7054", "PWY-7962", "PWY-7377", "PWY-7376", "PWY-8512", "PWY-7706", "PWY-5196", "PWY-5921", "PWY-7221", "PWY-8502", "PWY-6219", "PWY-6233", "ASPARAGINE-BIOSYNTHESIS", "PWY490-4", "HISTSYN-PWY", "PWY-6318", "PWY-8449", "PWY-6466", "PWY-5297", "PWY-8504", "TRNA-CHARGING-PWY", "PWY-8229", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-8367", "PWY-7000", "PWY-7014", "PWY-7022", "PWY-6121", "PWY-6122", "PWY-6277", "PWY-4361", "PWY-6711", "PWY-5978", "PWY-5940", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% glutamine_pathways$Pathway) %>%
  left_join(glutamine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName, ncol = 6) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Glutamine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/glutamine.png", ., units = "px", width = 3800, height = 1500)

```


```{r glycine_pathways}

glycine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("CRNFORCAT-PWY", "PWY-4722", "PWY-3661", "PWY-4041", "PWY-7559", "PWY-8397", "PWY66-375", "PWY-4061", "PWY-6842", "PWY-7447", "PWY-7112", "PWY-8302", "PWY-5706", "PWY-8135", "CAMALEXIN-SYN", "PWY-8117", "PWY-8001", "PWY-1622", "PWY-7533", "PWYQT-4471", "PWYQT-4475", "PWY-1187", "PWYQT-4474", "PWY-2821", "PWYQT-4473", "PWYQT-4472", "PWY-601", "PWY-7901", "PWY-6842", "PWY-3661", "PWY-3661-1", "PWY-8325", "PWY-8551", "PWY-6841", "PWYQT-4477", "PWY-6100", "PWY-7614", "PWY-6021", "PWY-8355", "PWY-6745", "PWY-5707", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("GLYCGREAT-PWY", "PWY-8045", "PWY-7693", "PWY-8506", "PWY-6121", "PWY-6122", "PWY-6277", "PWY-5903", "PWY-8117", "PWY-8438", "PWY-8015", "P164-PWY", "PWY-8303", "PWY-7536", "PWY-5189", "PWY-8438", "PWY-8530", "PWY8J2-27", "PWY-7891", "PWY-7892", "PWY-8320", "PWY-7718", "PWY-8489", "PWY-5903", "PWY-6061", "PWY66-241", "PWY-7396", "PWY-5679", "PWY-8438", "PWY-7571", "PWY-7577", "GLUTATHIONESYN-PWY", "P541-PWY", "PWY-8082", "PWY-6649", "PWY-7910", "PWY-6318", "PWY2G6Z-4", "PWY-8532", "PWY-8043", "PWY-8049", "PWY0-1586", "PWY-7351", "PWY-7671", "PWY-8366", "PWY-7751", "PWY1A0-6120", "PWY-6891", "PWY-6909", "PWY-8308", "PWY-7737", "PWY-7991", "TRNA-CHARGING-PWY", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY66-385", "PWY-2161", "PWY-2201", "PWY-3841", "1CMET2-PWY", "PWY-1622", "PWY-3661", "PWY-3661-1", "PWY-8325", "GLYSYN-PWY", "PWY0-1608", "PWY-181", "PWY-8362", "PWY-8363", "PWY-5497", "PWY-2201", "GLYCINE-SYN2-PWY", "GLYCLEAV-PWY", "PWY0-1608", "PWY-8303", "PWY-1622", "PWY-8011", "GLYSYN-THR-PWY", "PWY-5436", "P164-PWY", "PWY-5497", "GLYSYN-ALA-PWY", "THREONINE-DEG2-PWY", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% glycine_pathways$Pathway) %>%
  left_join(glycine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Glycine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/glycine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r histidine_pathways}

histidine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("HISTSYN-PWY", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("HISDEG-PWY", "PWY-5028", "PWY-5030", "HISHP-PWY", "PWY-7255", "PWY-7750", "PWY66-420", "PWY-6173", "PWY66-421", "PWY-7605", "TRNA-CHARGING-PWY", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-5029", "HISTDEG-PWY", "PWY-5031", "PWY-8007", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% histidine_pathways$Pathway) %>%
  left_join(histidine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Histidine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/histidine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r isoleucine_pathways}

isoleucine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-7859", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-8523", "TRNA-CHARGING-PWY", "PWY-6220", "PWY-6233", "PWY-8496", "PWY-7667", "PWY-8361", "PWY-7706", "PWY-8543", "PWY-6679", "PWY-5990", "PWY-8498", "PWY-8495", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-8173", "ILEUSYN-PWY", "PWY-5101", "PWY-5103", "PWY-5104", "PWY-5108", "ILEUDEG-PWY", "PWY-5078", "PWY-8184", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% isoleucine_pathways$Pathway) %>%
  left_join(isoleucine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Isoleucine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/isoleucine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r leucine_pathways}

leucine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-7569", "PWY-7570", "PWY-1822", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-6220", "PWY-6233", "PWY-7648", "PWY-7569", "PWY-7665", "PWY-7570", "PWY-8443", "PWY-7706", "PWY-8543", "PWY-6003", "PWY-6219", "PWY-8081", "PWY-7769", "PWY-7441", "PWY-8563", "TRNA-CHARGING-PWY", "PWY-7694", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("LEUSYN-PWY", "LEU-DEG2-PWY", "PWY-5076", "PWY-7767", "PWY-8185", "PWY-8174", "PWY-8525", "PWY-5075", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% leucine_pathways$Pathway) %>%
  left_join(leucine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Leucine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/leucine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r lysine_pathways}

lysine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("DAPLYSINESYN-PWY", "PWY-2941", "PWY-2942", "PWY-5097", "PWY0-521", "PWY1QP9-2", "LYSINE-AMINOAD-PWY", "PWY-3081", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY0-1303", "PWY-8558", "PWY-6381", "PWY0-1601", "PWY-6376", "PWY-6375", "PWY0-461", "PWY-6328", "PWY-5468", "PWY-7861", "PWY66-425", "AEROBACTINSYN-PWY", "PWY185E-1", "PWY-8494", "PWY-8495", "PWY-8492", "PWY-8496", "PWY-7667", "PWY-7668", "PWY66-425", "PWY-5311", "PWY-8320", "PWY-8297", "PWY-8424", "PWY1QP9-2", "LYSDEGII-PWY", "PWY-5280", "PWY-5314", "LYSINE-DEG1-PWY", "P163-PWY", "PWY-6994", "PWY-8383", "PWY-6409", "PWY-8450", "TRNA-CHARGING-PWY", "PWY-6386", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-7380", "PWY-5324", "PWY-5283", "PWY-5298", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% lysine_pathways$Pathway) %>%
  left_join(lysine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Lysine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/lysine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r methionine_pathways}

methionine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-2201", "PWY-3841", "1CMET2-PWY", "HOMOSER-METSYN-PWY", "HSERMETANA-PWY", "ADENOSYLHOMOCYSCAT-PWY", "PWY-6151", "PWY-5041", "HOMOSER-METSYN-PWY", "PWY-702", "HSERMETANA-PWY", "PWY-7729", "PWY-8097", "PWY-8095", "PWY-8096", "PWY-8113", "PWY-8112", "PWY-5198", "PWY0-1507", "PWY-7380", "PWY-8128", "PWY-3661", "PWY-3661-1", "ADENOSYLHOMOCYSCAT-PWY", "PWY0-501", "PWY0-1275", "PWY-6987", "PWY-5531", "HEMESYN2-PWY", "PWY-7374", "PWY-7371", "PWY-8364", "PWY-7864", "PWY-7286", "PWY-7285", "PWY-7174", "PWY-8132", "PWY-7800", "PWY-7799", "PWY-6942", "PWY-8504", "ADENOSYLHOMOCYSCAT-PWY", "PWY-5441", "PWY-7382", "PWY0-501-1", "PWY0-1533", "PWY-7399", "PWY-6700", "PWY-8106", "PWY-6829", "PWY-7888", "PWY-7805", "PWY-5531", "PWY-6890", "PWY-8364", "PWY-7800", "PWY-7760", "PWY-8368", "PWY-7710", "PWY-6644", "PWY-5757", "PWY-7025", "PWY-8414", "PWY-7807", "PWY-7552", "PWY-7554", "PWY-7846", "PWY-7072", "PWY-8367", "PWY-8540", "PWY-7977", "PWY-6828", "PWY-7382", "PWY-8415", "PWY-8482", "PWY-6823", "PWY-8122", "PWY-8499", "PWY-7022", "PWY-7769", "PWY-6322", "PWY-6420", "PWY-8106", "PWY-8504", "PWY-6148", "PWY-6892", "PWY-8481", "PWY-8562", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-5912", "PWY-6151", "PWY-5041", "ETHYL-PWY", "METHIONINE-DEG1-PWY", "SAM-PWY", "PWY-6054", "PWY-6055", "PWY-5441", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-7793", "PWY-701", "PWY-8543", "PWY-7025", "PWY-701", "PWY-7708", "TRNA-CHARGING-PWY", "PWY-7694", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-4361", "PWY-5082", "PWY-6627", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% methionine_pathways$Pathway) %>%
  left_join(methionine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Methionine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/methionine.png", ., units = "px", width = 2800, height = 1400)
  

```


```{r phenylalanine_pathways}

phenylalanine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("PWY-8454", "PWY-3462", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-8157", "PWY-6444", "PWY-6457", "PWY-5883", "PWY1F-467", "PWY-5048", "PWY-1121", "PWY-6495", "PWY-8527", "PWY-2821", "PWY-7824", "PWY-2821", "PWY-7824", "PWY-5788", "PWY-6219", "PHENYLALANINE-DEG1-PWY", "PWY-6134", "PWY-6318", "PWY-5751", "PWY-8523", "PWY-8494", "PWY-8492", "PWY-8496", "PWY-7668", "PWY-7665", "PWY-7626", "PWY-6495", "PWY-8543", "PWY-7533", "PWY-6003", "PWY-6220", "PWY-8529", "PWY-7158", "PWY-8370", "PWY-8116", "PWY-8495", "PWY-8528", "PWY-8527", "PWY-5660", "PWY-5751", "PWY-8531", "TRNA-CHARGING-PWY", "PWY-7704", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PHESYN", "ANAPHENOXI-PWY", "PWY-5079", "PWY-6318", "PWY-8014", "PWY-8565", "PWY-8529", "PWY-7275", "PWY-5079", "PWY-7432", "PWY-5317", "PWY-5081", "PWY-7520", "PWY-5082", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% phenylalanine_pathways$Pathway) %>%
  left_join(phenylalanine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Phenylalanine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/phenylalanine.png", ., units = "px", width = 2800, height = 1400)


```


```{r proline_pathways}

proline_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("ARG-PRO-PWY", "PWY-8187", "PROSYN-PWY", "PWY-3341", "ARG-GLU-PWY", "ORN-AMINOPENTANOATE-CAT-PWY", "PWY-4981", "PWY-7515", "PWY-4281", "P561-PWY", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-5737", "PWY-6922", "CITRULBIO-PWY", "PROUT-PWY", "PWY-8368", "PWY-6495", "PWY-7930", "PWY-8210", "PWY-7525", "PWY-8345", "PWY-8210", "PWY-8524", "PWY-7718", "PWY-8361", "PWY-7665", "PWY-7931", "PWY-8368", "PWY-6495", "PWY-6003", "PWY-8498", "PWY-7547", "PWY0-1544", "PWY-7930", "PWY1A0-6120", "TRNA-CHARGING-PWY", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY-8186", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% proline_pathways$Pathway) %>%
  left_join(proline_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Proline Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/proline.png", ., units = "px", width = 2800, height = 1400)


```


```{r serine_pathways}

serine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("SERSYN-PWY", "PWY-6955", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-8071", "PWY-7274", "CYSTSYN-PWY", "PWY-I9", "PWY-7870", "PWY-6936", "PWY-8117", "ENTBACSYN-PWY", "PWY-8484", "PWY-7751", "PWY-7987", "PWY-3661", "PWY-8325", "PWY0-1608", "SERDEG-PWY", "PWY-5497", "PWY-3385", "PWY-3542", "PWY4FS-6", "PWY-7782", "PWY-7706", "PWY-8008", "PWY-8381", "PWY-7694", "PWY-5497", "PWY3DJ-12", "PWY-5129", "SPHINGOLIPID-SYN-PWY", "PWY-7693", "PWY-7987", "PWY-7694", "PWY0-901", "PWY-6281", "PWY-5669", "PHOSLIPSYN2-PWY", "PWY-6574", "PWY-6141", "PWY-8117", "PWY-7735", "ENTBACSYN-PWY", "PWY-7669", "PWY-7571", "PWY-8484", "PWY-1622", "PWY-7533", "PWY-8551", "PWY-8009", "TRPSYN-PWY", "PWY-1", "PWY-7797", "PWY-7501", "PWY-7547", "PWY-6409", "SPHINGOLIPID-SYN-PWY", "PWY1A0-6120", "TRNA-CHARGING-PWY", "PWY-8229", "PWY-7694", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("PWY66-385", "PWY-2161", "PWY-2201", "PWY-3841", "1CMET2-PWY", "PWY-1622", "PWY-3661", "PWY-3661-1", "PWY-8325", "GLYSYN-PWY", "PWY0-1608", "PWY-181", "PWY-8362", "PWY-8363", "PWY-5497", "PWY-1622", "PWY-8011", "PWY-181", "PWY-6273", "PWY-7506", "PHOSLIPSYN2-PWY", "PWY-801", "HOMOCYSDEGR-PWY", "PWY66-426", "PWY-8359", "PWY-8140", "PWY-6455", "PWY-8011", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% serine_pathways$Pathway) %>%
  left_join(serine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Serine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/serine.png", ., units = "px", width = 2800, height = 1400)


```


```{r threonine_pathways}

threonine_pathways <- data.frame(Type = c("Synthesis"), Pathway = c("HOMOSER-THRESYN-PWY", "PWY-7954", "PWY-6053", "PWY-6854", "PWY-1186", "PWY-6054", "PWY-4041", "PWY-8455", "PWY-7465", "PWY-7269", "PWY-7367")) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c("PWY-8443", "PWY-5826", "ILEUSYN-PWY", "PWY-5437", "PWY66-428", "PWY-7984", "PWY-5903", "PWY-7983", "PWY-7378", "THREONINE-DEG2-PWY", "THRDLCTCAT-PWY", "PWY-5826", "ILEUSYN-PWY", "PWY-5437", "PWY-8526", "PWY-5443", "PWY-7984", "PWY185E-1", "PWY-7378", "THRDLCTCAT-PWY", "PWY-7718", "PWY-8374", "PWY-5903", "P241-PWY", "PWY-7650", "PWY-6644", "PWY-8498", "PWY-7441", "PWY-7658", "PWY-7983", "PWY-6409", "PWY-7954", "TRNA-CHARGING-PWY", "PWY-6374", "PWY-4041", "PWY66-375", "PWY-8355", "PWY-7701", "PWY-8455", "PWY-7547", "PWY-7510", "PWY-7649"))) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c("GLYSYN-THR-PWY", "PWY-5436", "PWY0-1587", "PWYQT-4450", "PWY-4002", "PWY-1186", "PWY-7119")))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% threonine_pathways$Pathway) %>%
  left_join(threonine_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Threonine Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/threonine.png", ., units = "px", width = 2800, height = 1400)


```


```{r tryptophan_pathways}

tryptophan_pathways <- data.frame(Type = c("Synthesis"), Pathway = c()) %>%
  rbind(data.frame(Type = c("Consumption"), Pathway = c())) %>%
  rbind(data.frame(Type = c("Both"), Pathway = c()))

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% tryptophan_pathways$Pathway) %>%
  left_join(tryptophan_pathways, by = "Pathway", multiple = "last") %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`, fill = `Type`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Tryptophan Pathways")) %>%
  
  ggsave("graphs/humann/specific/AminoAcids/tryptophan.png", ., units = "px", width = 2800, height = 1400)


```

```{r glutamine_synthesis}

# well ok, there's none of these

glutamine_synthesis_pathways <- c("AMMASSIM-PWY", "PWY-8291", "PWY-8294", "GLNSYN-PWY")

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% glutamine_synthesis_pathways) %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Synthesis of Glutamine")) %>%
  
  ggsave("graphs/humann/glutamine_synthesis.png", ., units = "px", width = 2400, height = 1400)
  


```

```{r glutamine_consumption}

glutamine_consumption_pathways <- c("PWY-6121", "PWY-6122", "PWY-6277", "AMMASSIM-PWY", "GLUTSYN-PWY", "GLUTAMINDEG-PWY", "PYRIDNUCSYN-PWY", "PYRIDNUCSAL-PWY", "PWY-7761", "ARGSYN-PWY", "PWY-5686", "PWY-6543", "PWY-7221", "ASPARAGINE-BIOSYNTHESIS", "HISTSYN-PWY", "TRPSYN-PWY", "TRNA-CHARGING-PWY", "UDPNAGSYN-PWY", "PWY-7176")

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% glutamine_consumption_pathways) %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Consumption of Glutamine")) %>%
  
  ggsave("graphs/humann/glutamine_consumption.png", ., units = "px", width = 2400, height = 1400)
  

```

```{r histidine_consumption}

histidine_consumption_pathways <- c("HISDEG-PWY", "HISTDEG-PWY", "PWY-5028", "PWY-5030", "PWY-5031", "HISHP-PWY")

(humann_prodigal_community_with_metadata %>% 
  filter(Pathway %in% histidine_consumption_pathways) %>%
  #aggregate(`Relative Abundance` ~ SampleName, FUN = sum)
    
  ggplot(aes(x = `PathwayDescription`, y = `Relative Abundance`)) + 
    geom_bar(stat = "identity") + 
    facet_wrap(. ~ SampleName) + 
    coord_flip() + 
    ggtitle("Pathway Abundance - Consumption of Histidine")) %>%
  
  ggsave("graphs/humann/histidine_consumption.png", ., units = "px", width = 2400, height = 1400)
  

```

```{r urocanate_hydratase_genes}

# breaks down urocanate

urocanate_hydratase_genes <- read_tsv("data/humann/urocanate_hydratase.tsv")

(humann_prodigal_genefamilies %>% 
    filter(`Gene Family` %in% paste0("UniRef90_", urocanate_hydratase_genes$Entry)) %>%
  
    ggplot(aes(x = `Gene Family`, y = `RPKs`)) + 
      geom_bar(stat = "identity") + 
      facet_wrap(. ~ SampleName) + 
      coord_flip() + 
    ggtitle("Gene Abundance - Urocanate Hydratase")) %>%
  
  ggsave("graphs/humann/urocanate_hydratase_genes.png", ., units = "px", width = 2400, height = 2800)


```

```{r histidine_ammonia_lyase_genes}

# produces urocanate

histidine_ammonia_lyase_genes <- read_tsv("data/humann/histidine_ammonia_lyase.tsv")

(humann_prodigal_genefamilies %>% 
    filter(`Gene Family` %in% paste0("UniRef90_", histidine_ammonia_lyase_genes$Entry)) %>%
  
    ggplot(aes(x = `Gene Family`, y = `RPKs`)) + 
      geom_bar(stat = "identity") + 
      facet_wrap(. ~ SampleName) + 
      coord_flip() + 
    ggtitle("Gene Abundance - Histidine Ammonia-Lyase")) %>%
  
  ggsave("graphs/humann/histidine_ammonia_lyase_genes.png", ., units = "px", width = 2400, height = 2800)


```