---
title: "LOMA Analysis"
author: "Alex Caswell"
date: "2025-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}

source("get_stats_from_readqc.r")

library(ggtext)
library(sitools)
library(cowplot)
library(ggExtra)
library(ggpmisc)

```

# What's the plan?!

We need...

-   Read statistics for every input file (*b.p., n50, \# reads, filesize*)
-   Assembly information
    -   \# of contigs
    -   \# of bins
-   *Diversity information*
    -   Shannon/Inv. Simpson

```{r read_statistics}

read_statistics <- get_tsv_from_run_folder("/data/loma/RUN01_raman/")
read_statistics <- read_statistics %>%
  mutate(mean_bin_bp = total_binned_bp/bin_count) %>%
  mutate(run_accession = str_extract(run_accession, "[R]+[0-9]+"))

```

```{r get_assembly_stats}

assembly_stats <- get_all_assembly_stats("data/loma/RUN01_raman")

```

```{r histogram_of_n50}

histogram_of_n50 <- ggplot(read_statistics, aes(x=read_n50)) +
  geom_histogram(binwidth=1000, boundary = 0, closed = "left", col="grey") + 
  theme_classic() +
  scale_fill_brewer(palette = "Set1") + 
  ylab("Count") + 
  xlab("N50") + 
  scale_x_continuous(breaks = seq(0, 30000, 2000)) +
  theme(
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
  )

ggsave("graphs/loma/example/histogram_n50.png", histogram_of_n50, width = 2100, height = 1600, units="px")
histogram_of_n50

```

```{r histogram_of_number_of_reads}

histogram_of_number_of_reads <- ggplot(read_statistics, aes(x=number_of_reads)) +
  geom_histogram(binwidth=1000000, boundary = 0, closed = "left", col="grey") + 
  theme_classic() +
  scale_fill_brewer(palette = "Set1") + 
  ylab("") + 
  xlab("Number of Reads") + 
  scale_x_continuous(breaks = seq(0, 18000000, 2000000), labels=f2si) +
  theme(
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
  )

ggsave("graphs/loma/example/histogram_of_number_of_reads.png", histogram_of_number_of_reads, width = 2100, height = 1600, units="px")
histogram_of_number_of_reads

```


```{r histogram_of_total_bases}

histogram_of_total_bases <- ggplot(read_statistics, aes(x=total_bases_mbp)) +
  geom_histogram(binwidth=2000, boundary = 0, closed = "left", col="grey") + 
  theme_classic() +
  scale_fill_brewer(palette = "Set1") + 
  ylab("Count") + 
  xlab("Total Bases (Mbp)") + 
  scale_x_continuous(breaks = seq(0, 60000, 10000), labels=f2si) +
  theme(
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
  )

ggsave("graphs/loma/example/histogram_of_total_bases.png", histogram_of_total_bases, width = 2100, height = 1600, units="px")
histogram_of_total_bases

```

```{r make_sequencing_stats_panel}

sequencing_stats_panel <- plot_grid(plot_grid(histogram_of_total_bases, histogram_of_number_of_reads, labels=c("A", "B")), histogram_of_n50, ncol=1, labels=c("", "C"))
ggsave("graphs/loma/example/sequencing_stats_panel.png", sequencing_stats_panel, height=2100, width=3200, units="px")

```

```{r integrated_sequencing_stats}

integrated_scatter <- ggplot(read_statistics, aes(x=read_n50, y=number_of_reads, size = total_bases_mbp)) +
  geom_point() + 
  theme_classic() +
  scale_x_continuous(breaks = seq(0, 30000, 2000), labels=f2si) +
  scale_y_continuous(breaks = seq(0, 40000000, 4000000), labels=format_si()) +
  scale_size_continuous(name="Total Bases (Mbp)") +
  xlab("N50") +
  ylab("Number of Reads") +
  theme(
    legend.position = "left"
  )

marginal_integrated_scatter <- ggMarginal(integrated_scatter, type="histogram")
ggsave("graphs/loma/example/marginal_integrated_scatter.png", marginal_integrated_scatter)
marginal_integrated_scatter
```

```{r make_graphs}


filtered_read_statistics <- read_statistics[read_statistics$bin_count != 0,]

make_ggplot_scatterplot(filtered_read_statistics, filtered_read_statistics$total_bases_mbp, filtered_read_statistics$bin_count) + 
  geom_point(aes(color = "red")) + 
  xlab("Total Bases (mbp)") + 
  ylab("Number of bins")

make_ggplot_scatterplot(filtered_read_statistics, filtered_read_statistics$read_n50, filtered_read_statistics$average_bin_n50) + 
  geom_point(aes(color = "red")) + 
  #geom_smooth(method = "lm", alpha = 0.1) +
  xlab("Input Read N50") + 
  ylab("Average Bin N50")


```

```{r compare_bin_count_to_x}


bases_bincount <- ggplot(filtered_read_statistics, aes(x = (total_bases_mbp/1000), y = bin_count)) + 
  stat_poly_line() +
  stat_poly_eq(use_label(c("R2", "p"))) +
  geom_point() + 
  xlab("<b>Total Bases</b> (<i>Gbp</i>)") + 
  ylab("<b>Number of Bins</b>") + 
  ggtitle("<b>More sequencing</b> produces <b>more bins</b>.") +
  scale_y_continuous(breaks = seq(0, 600, 100)) +
  theme_classic() + 
  theme(
    axis.title.x = element_markdown(hjust = 0.1, size = 13),
    axis.title.y = element_markdown(hjust = 0.1, size = 13),
    plot.title = element_markdown(hjust = 0.5, size = 16)
  )

ggplot(filtered_read_statistics, aes(x = number_of_reads, y = bin_count)) + 
  geom_point()

ggplot(filtered_read_statistics, aes(x = read_n50, y = bin_count)) + 
  geom_point()

ggplot(filtered_read_statistics, aes(x = mean_read_length, y = bin_count)) + 
  geom_point()

ggsave("graphs/loma/example/bases_bincount.png", bases_bincount)
bases_bincount

```

```{r compare_bin_n50_to_x}


ggplot(filtered_read_statistics, aes(x = total_bases_mbp, y = average_bin_n50)) + 
  geom_point()

ggplot(filtered_read_statistics, aes(x = number_of_reads, y = average_bin_n50)) + 
  geom_point()

in_out_n50 <- ggplot(filtered_read_statistics, aes(x = round(10*read_n50/1000)/10, y = round(10*average_bin_n50/1000)/10)) + 
  stat_poly_line() +
  stat_poly_eq(use_label(c("R2", "p"))) +
  geom_point() + 
  xlab("<b>N50 of reads</b> (<i>Kbp</i>)") + 
  ylab("<b>N50 of bins</b> (<i>Kbp</i>)") + 
  ggtitle("<b>Longer reads</b> produce <b>more contiguous</b> bins.") +
  scale_x_continuous(breaks = seq(0, 30, 5)) +
  theme_classic() + 
  theme(
    axis.title.x = element_markdown(hjust = 0.1, size = 13),
    axis.title.y = element_markdown(hjust = 0.1, size = 13),
    plot.title = element_markdown(hjust = 0.5, size = 16)
  )

ggplot(filtered_read_statistics, aes(x = mean_read_length, y = average_bin_n50)) + 
  geom_point()

ggsave("graphs/loma/example/in_out_n50.png", in_out_n50)
in_out_n50

```

``` {r make_example_bins_panel}

binning_panel <- plot_grid(bases_bincount, in_out_n50, labels = c("A", "B"), rel_widths = c(0.95, 1))

ggsave("graphs/loma/example/binning_panel.png", binning_panel, width = 3000, height = 1400, units = "px")
binning_panel

```


```{r number_of_bins}


number_of_bins <- ggplot(read_statistics, aes(x = run_accession, y = bin_count)) + 
  geom_bar(stat="identity", colour = "black", show.legend = FALSE, fill="grey") +
  geom_text(label = read_statistics$bin_count, size = 6, vjust = -0.2) +
#  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("R003", "R004", "R005", "R007", "R012", "R018")) +
  ylab("Total \\# of Genome Bins") +
  xlab("") +
  expand_limits(y = c(0, 300)) +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 14),
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef00'),
    plot.background = element_rect(fill = '#fff7ef00'),
    legend.background = element_rect(fill = '#fff7ef00'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank()
  )

number_of_bins
ggsave("graphs/loma/number_of_bins.png", number_of_bins)

```


```{r number_of_contigs}


number_of_contigs <- ggplot(read_statistics, aes(x = run_accession, y = contig_count, fill = run_accession)) + 
  geom_bar(stat="identity", show.legend = TRUE) +
  geom_text(label = read_statistics$contig_count, size = 6, vjust = -0.2) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("R003", "R004", "R005", "R007", "R012", "R018")) +
  scale_y_continuous(labels = format_si()) +
  ylab("Total \\# of Assembled Contigs") +
  xlab("") +
  expand_limits(y = c(0, 18000)) +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 20),
    axis.title.x = element_markdown(size = 10),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef'),
    plot.background = element_rect(fill = '#fff7ef'),
    legend.background = element_rect(fill = '#fff7ef'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank()
  )

number_of_contigs
ggsave("graphs/loma/number_of_contigs.png", number_of_contigs)

```

```{r bin_n50}


bin_n50 <- ggplot(read_statistics[Complete > 50, ], aes(x = run_accession, y = round(average_bin_n50/1000))) + 
  geom_bar(stat="identity", show.legend = FALSE, colour="black", fill="grey") +
  geom_text(label = round(read_statistics$average_bin_n50/1000), size = 6, vjust = -0.2) +
#  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("R003", "R004", "R005", "R007", "R012", "R018")) +
  scale_y_continuous(labels = format_si()) +
  ylab("Average Bin N50 (Kbp)") +
  xlab("") +
  expand_limits(y = c(0, 800)) +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 14),
    axis.title.x = element_markdown(size = 10),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef00'),
    plot.background = element_rect(fill = '#fff7ef00'),
    legend.background = element_rect(fill = '#fff7ef00'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank()
  )

bin_n50
ggsave("graphs/loma/bin_n50.png", bin_n50)

```

```{r number_of_bins_and_n50_panel}

number_of_bins_and_n50_panel <- plot_grid(number_of_bins, bin_n50, labels = c("A", "B"), rel_widths = c(1, 1))

ggsave("graphs/loma/number_of_bins_and_n50_panel.png", number_of_bins_and_n50_panel, units = "px", width=2800, height=1200)
number_of_bins_and_n50_panel

```

```{r average_bin_bp}


bin_bp <- ggplot(read_statistics, aes(x = run_accession, y = round(100*mean_bin_bp/1000000)/100, fill = run_accession)) + 
  geom_bar(stat="identity", show.legend = TRUE) +
  geom_text(label = round(100*read_statistics$mean_bin_bp/1000000)/100, size = 6, vjust = -0.2) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("R003", "R004", "R005", "R007", "R012", "R018")) +
  scale_y_continuous(labels = format_si()) +
  ylab("Average Bin Size (Mbp)") +
  xlab("") +
  expand_limits(y = c(0, 3)) +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 20),
    axis.title.x = element_markdown(size = 10),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef'),
    plot.background = element_rect(fill = '#fff7ef'),
    legend.background = element_rect(fill = '#fff7ef'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank()
  )

bin_bp
ggsave("graphs/loma/bin_bp.png", bin_bp)

```

```{r bin_size_boxplot}

bin_size_boxplot <- ggplot(assembly_stats, aes(x = sampleid, y = round(100*assembly_length_bp/1000000)/100, fill=sampleid)) + 
  geom_boxplot(alpha = 0.7, show.legend = TRUE) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("R003", "R004", "R005", "R007", "R012", "R018")) +
  scale_y_continuous(labels = format_si()) +
  ylab("Average Bin Size (Mbp)") +
  xlab("") +
  expand_limits(y = c(0, 3)) +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 20),
    axis.title.x = element_markdown(size = 10),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef'),
    plot.background = element_rect(fill = '#fff7ef'),
    legend.background = element_rect(fill = '#fff7ef'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank()
  )

bin_size_boxplot
ggsave("graphs/loma/bin_size_boxplot.png", bin_size_boxplot)

```

```{r histogram_of_all_bins_n50}

all_bins_n50 <- ggplot(assembly_stats, aes(x = contig_N50_bp, fill = sampleid)) + 
  geom_histogram(boundary = 0, closed = "left", col="grey") +
  scale_x_continuous(labels = format_si()) +
  ylab("\\# of MAGs") +
  xlab("Contig N50 (b.p.)") +
  theme_classic() +
  theme(
    axis.text.y = element_markdown(size = 16),
    axis.text.x = element_markdown(size = 20),
    axis.title.x = element_markdown(size = 20),
    axis.title.y = element_markdown(size = 20),
    panel.spacing = unit(1, "lines"),
    strip.text = element_markdown(face = "bold", size = 12),
    panel.background = element_rect(fill = '#fff7ef00'),
    plot.background = element_rect(fill = '#fff7ef00'),
    legend.background = element_rect(fill = '#fff7ef00'),
    legend.text = element_markdown(size = 12),
    legend.title = element_blank()
  )

all_bins_n50

```
